version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - mvn install
  post_build:
    commands:
      - echo Build completed on `date`
      - mkdir builds
      - cp cli/target/cli-1.0-jar-with-dependencies.jar sokrates.jar
      - cp codeexplorer/target/codeexplorer-1.0-jar-with-dependencies.jar sokrates-explorer.jar
      - cp sokrates.jar sokrates-LATEST.jar
      - cp sokrates-explorer.jar sokrates-explorer-LATEST.jar
artifacts:
  files:
    - sokrates.jar
    - sokrates-explorer.jar
    - sokrates-LATEST.jar
    - sokrates-explorer-LATEST.jar
